version: "3"
services:
    backend:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "8891:8891"
        networks:
            - trovn-network

    frontend:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - backend
        networks:
            - trovn-network

networks:
    trovn-network:
        driver: bridge
